[[main]]
  identifier = 'home'
  name = 'Home'
  pageRef = '/'
  weight = 1

[[main]]
  identifier = 'blog'
  name = 'Blog'
  pageRef = '/blog'
  weight = 2

[[main]]
  identifier = 'posts'
  name = 'Posts'
  pageRef = '/posts'
  weight = 3

[[main]]
  identifier = 'reviews'
  name = 'Reviews'
  pageRef = '/posts/reviews'
  weight = 4

[[main]]
  identifier = 'docs'
  name = 'Docs'
  url = 'https://docs.jccpalmer.com'
  weight = 5
  [main.params]
    rel = 'external'