[[main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 20

[[main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 30

[[main]]
  name = 'Reviews'
  pageRef = '/posts/reviews'
  weight = 40

[[main]]
  name = 'Docs'
  url = 'https://docs.jccpalmer.com'
  weight = 50
  [main.params]
    rel = 'external'